### PR TITLE
add Chinese Simplified (zh_CN) translation

### PR DESCRIPTION
**Pull request by TylerTemp**
Add Chinese Simplified (zh_CN, used in China mainland) translation

Could you please also update the Chinese description of this app in Jolla Store? Thx:

* * * * * * * *

*简单的绘画工具*

有天晚上我想画点涂鸦，但是我没找到这样的应用，于是我启动了我的软件开发工具包。

这就是我弄出来的东西。

你是否曾发现过Jolla的BUG，截了个屏，但是有些隐私信息在上面？手头又没有电脑？但又很想快点说出来？这个绘画应用可以拯救你！现在你可以导入图片作为背景，在上面写文字甚至画上标尺——你只需要画一个标尺，其它的都能根据这个自动缩放。

### CODE REVIEW

**Comment by kimmoli** [comment]
Thanks!

**Comment by kimmoli** [comment]
@TylerTemp  Can you also provide translation for this short changelog:

0.7.0
- Option to remember tool settings
- Simplified chinese translation

**Comment by TylerTemp** [comment]
YES :)

the short changelog:

* * * * * * * * * * * * *

0.7.0
* 可选记住工具设置
* 添加简体中文翻译

**Comment by kimmoli** [comment]
@TylerTemp One translation "placeholder" was meant for credits of translator, not to be translated directly.
https://www.transifex.com/projects/p/paint

**Comment by kimmoli** [comment]
@TylerTemp one new string to translate

**Comment by TylerTemp** [comment]
Already send the "join group" request. Thx for info. And thx for the transifex project.

**Comment by kimmoli** [comment]
Ah ok, approved.

**Pull request merged**
